### ISSUE TITLE
custom permalinks input box missing / disappears

### ISSUE THREAD

**Issue by codemonkeynorth** [samiahmedsiddiqui/custom-permalinks#41] opened 2020-09-05 21:29 UTC
The meta box does not show. I can temporarily enable it but the input field is missing

When I reload the page, I can see the metabox appear briefly (without the input field) then the whole metabox disappears again

* Wordpress 5.4.2
* Custom Permalinks 1.7.1
* Disable Gutenberg 2.2
* ACF Pro 5.9.0
* ACF Extended 0.8.7.2

![image](https://user-images.githubusercontent.com/20189985/92313650-02eef800-efc6-11ea-8471-4bf0fe533b5e.png)
![image](https://user-images.githubusercontent.com/20189985/92313670-3d589500-efc6-11ea-9367-31f31062a5e7.png)

I also can't see the "slug" field: I'm assuming Custom Permalinks removes it?

any ideas?

essentially I need the custom permalink so i can remove the '/landing/' prefix from the Custom Post Type URLs

Landing Page CPT setup:

```register_post_type( 'landing', array(

	'labels' => array(
		'name' => __( 'Landing Pages', 'app' ),
		'singular_name' => __( 'Landing page', 'app' ),
	),
	'description' => '',
	'public' => true,
	'publicly_queryable' => true,
	'show_ui' => true,
	'show_in_rest' => true,
	'rest_base' => '',
	'rest_controller_class' => 'WP_REST_Posts_Controller',
	'has_archive' => 'false',
	'show_in_menu' => true,
	'show_in_nav_menus' => true,
	'delete_with_user' => false,
	'exclude_from_search' => true,
	'capability_type' => 'post',
	'map_meta_cap' => true,
	'hierarchical' => false,
	'rewrite' => [ 'slug' => 'landing', 'with_front' => false ],
	'query_var' => true,
	'menu_icon' => 'dashicons-admin-page',
	'supports' => [ 'title', 'editor', 'thumbnail', 'page-attributes' ],
));```

thanks
J

**Comment by codemonkeynorth** [comment] 2020-09-05 21:44
as you can see the metabox div for Custom Permalinks is empty:
![image](https://user-images.githubusercontent.com/20189985/92313910-00da6880-efc9-11ea-9b65-24c802839f9e.png)

Advanced Custom Fields PRO: 5.9.0
Advanced Custom Fields: Extended 0.8.7.2
Custom Permalinks: 1.7.1
Disable Gutenberg: 2.2
Yoast Duplicate Post: 3.2.5
Yoast SEO: 14.9

**Comment by codemonkeynorth** [comment] 2020-09-06 17:31
appears to be a conflict with Disable Gutenberg 2.2
https://wordpress.org/plugins/disable-gutenberg/

if i deactivate this, i get a custom permalink input box

I will raise with him as well

**Comment by samiahmedsiddiqui** [comment] 2020-09-07 19:52
Hi @codemonkeynorth 

Thank you for reaching out to me. You are not seeing the field in the meta box because when the Gutenberg is disabled **Custom Permalinks** overrides the default WP Permalink field which shows right below the post title but in your case I am not seeing that field.

Please check your browser console or share your browser console screenshot to verify there is no JS issue. Also, disable the Custom Permalinks plugin and check whether you are seeing the default WP Permalink field or not.

Thanks and Regards,
Sami

**Comment by samiahmedsiddiqui** [comment] 2020-09-25 09:20
@samiahmedsiddiqui Is there any update on this issue?

**Comment by codemonkeynorth** [comment] 2020-09-25 10:02
@samiahmedsiddiqui sorry, I’ll get back to you shortly on this. I need to prep a test site

**Comment by samiahmedsiddiqui** [comment] 2020-09-25 12:41
> @samiahmedsiddiqui sorry, I’ll get back to you shortly on this. I need to prep a test site

Let me know once the setup is complete

**Comment by codemonkeynorth** [comment] 2020-09-30 23:54
Hi @samiahmedsiddiqui 

I think the problem is when gutenberg is disabled via code...

 `add_filter("use_block_editor_for_post_type", "disable_gutenberg_editor");function disable_gutenberg_editor() { return false; }`

I think your plugin does not understand this parameter enough to work out that gutenberg isn't present? (I believe all the plugins use that method under the hood)

I shall investigate further

thanks
J


### Scenario 1
**Custom Permalinks Enabled / Gutenberg disabled** (broken)
![image](https://user-images.githubusercontent.com/20189985/94750111-46e2dc00-037d-11eb-9125-4dfaeabfdc25.png)
source:
```
<div id="custom-permalinks-edit-box" class="postbox  hide-if-js" >
<button type="button" class="handlediv" aria-expanded="true"><span class="screen-reader-text">Toggle panel: Custom Permalinks</span><span class="toggle-indicator" aria-hidden="true"></span></button><h2 class="hndle"><span>Custom Permalinks</span></h2>
<div class="inside">
</div>
</div>
```

no console errors specifically
```
JQMIGRATE: Migrate is installed, version 1.4.1 (jquery-migrate.min.js?ver=1.4.1)
[Violation] 'DOMContentLoaded' handler took 1262ms (post-edit-1490.js)
[Violation] Forced reflow while executing JavaScript took 42ms
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952 (select2.full.min.js?ver=4.0.3)
[Violation] 'setTimeout' handler took 54ms (jQuery.js)
[Violation] Forced reflow while executing JavaScript took 48ms
[Violation] 'setTimeout' handler took 105ms (loadash.min.js?ver=4.17.15)
```

### Scenario 2
**Custom Permanlinks disabled / Gutenberg Enabled**
![image](https://user-images.githubusercontent.com/20189985/94750641-6fb7a100-037e-11eb-8944-5f4741a5cad0.png)
```
<div class="components-panel__row">
<label for="editor-post-slug-0">Slug</label>
<input type="text" id="editor-post-slug-0" class="editor-post-slug__input" value="test">
</div>
```

### Scenario 3
**Custom Permalinks enabled / Gutenberg Enabled**
![image](https://user-images.githubusercontent.com/20189985/94750895-0e440200-037f-11eb-8cce-b7230f0fb525.png)

**Comment by codemonkeynorth** [comment] 2020-10-01 00:01
Hi @samiahmedsiddiqui 

sorry possibly my bad.. I disabled ACF Pro 5.9.1 and the fields come back

I will see if I can work out if it's a config issue or if I need to pick this up with Elliot

thanks
J

### Scenario 4
**Custom Permalinks Enabled / Guternberg Disabled / ACF Pro Disabled**
![image](https://user-images.githubusercontent.com/20189985/94751857-857a9580-0381-11eb-92d3-bface15af30b.png)

**Comment by codemonkeynorth** [comment] 2020-10-01 00:20
Hi @samiahmedsiddiqui 

not sure about this.. it's not a problem, it just doesn't quite render in the right place?

(The Custom Permalinks Meta Box at the bottom is empty, but there's a box-less version at the top)

hope that helps anyway
thanks
J

### Scenario 5
**Custom Permalinks Enabled / Gutenberg Disabled / ACF Pro Enabled / no hidden fields (ACF setting)**
![image](https://user-images.githubusercontent.com/20189985/94752769-1488ad00-0384-11eb-8f8c-890f014da4a2.png)

**Comment by codemonkeynorth** [comment] 2020-10-01 00:40
*for reference ACF gives these options for each Custom Field setup)
https://www.hereswhatidid.com/media/acf-gotcha-hideonscreen.png

likely disabling `slug` or `permalink` broke it

**Comment by samiahmedsiddiqui** [comment] 2020-10-01 06:46
@codemonkeynorth If the Gutenberg is disabled then the Custom Permalinks Meta Box is empty and gets hidden. This is not a bug, this is what it is supposed to do. 

Actually with Classic Editor, Custom Permalinks override the WP default permalink field that shows up right below the title field (What you can see in your scenario 5 screenshot), this is the actual behavior and how does it had worked before WP 5.0 release (before Gutenberg). With Gutenberg, there is no way to override the WP default permalink that's why I introduced Custom Permalinks Meta Box but this meta box only worked with Gutenberg, With classic editor, functionality remain the same as it was before and the meta box should be hidden.

I don't know why the Custom Permalinks meta box is still showing you with the Classic Editor. It is not showing on my end. Can you please check this issue with this version?
https://github.com/samiahmedsiddiqui/custom-permalinks/releases/tag/v2.0.0-alpha

This is the alpha version of the plugin that will going to be released as the official version after some testing and might be few more changes.

> likely disabling slug or permalink broke it

If you disable `permalink` field that means WP default Permalink gets disabled and Custom Permalinks cannot override it. This is what people usually do when they don't want to show the Permalink field to their content writers etc.

Let me know if you have any other questions or need clarification in your any scenario. Also, please let me know the testing results of [v2.0.0-alpha](https://github.com/samiahmedsiddiqui/custom-permalinks/releases/tag/v2.0.0-alpha).

Thanks and Regards,
Sami

**Comment by codemonkeynorth** [comment] 2020-10-01 10:13
Hi @samiahmedsiddiqui 

Thanks for the detailed reply.

I think this is my mistake in the end, specifically from having ACF hiding fields accidentally.

The Custom Permalinks metabox does actually get hidden as you describe on page load, but I had then gone to “Screen Options” at the top of the page and enabled it, bringing back the empty meta box at the bottom 

I’ll try the new version though and let you know the results

Thanks
J

**Comment by samiahmedsiddiqui** [comment] 2020-10-01 10:54
> The Custom Permalinks metabox does actually get hidden as you describe on page load, but I had then gone to “Screen Options” at the top of the page and enabled it, bringing back the empty meta box at the bottom

Got it. 

> I’ll try the new version though and let you know the results

That would be great


Thanks, 
Sami

**Comment by codemonkeynorth** [comment] 2020-10-07 01:18
Hi 

Behaviour is the same, so as expected

Thanks
J

**Comment by samiahmedsiddiqui** [comment] 2020-10-07 05:43
Hi @codemonkeynorth Thank you for your response. I am closing this issue now.

**Closed by samiahmedsiddiqui** 2020-10-07 05:43 UTC
Labels: good first issue, question
